import Header from "./components/header";
import "./globals.css";
import Head from "next/head";

export const metadata = {
  title: "SoraBlog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#000000" />
        <meta
          name="description"
          content="Web site created using create next app"
        />
        <link rel="apple-touch-icon" href="/logo192.png" />
      </Head>
      <body className="bg-slate-800">
        <Header />
        {children}
        <footer className="text-center font-nsjp mb-8">
          ©2024 SoraBlog All rights reserved.
        </footer>
      </body>
    </html>
  );
}
