import "./globals.css";
import Head from "next/head";

export const metadata = {
  title: "SoraBlog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#000000" />
        <meta
          name="description"
          content="Web site created using create next app"
        />
        <link rel="apple-touch-icon" href="/logo192.png" />
      </Head>
      <body className="bg-slate-800">
        <header className="bg-slate-800 h-20 w-full p-0 pr-20 items-center flex">
          <h1 className="text-white font-nsjp text-5xl font-bold mb-4 ml-6">
            SoraBlog
          </h1>
          <div className="ml-auto mr-0 p-0 w-[24vw] flex justify-between">
            <button id="worksscrollButton">
              <h2 className="text-3xl font-nsjp font-semibold text-white">
                Works
              </h2>
            </button>
            <button id="contactscrollButton">
              <h2 className="text-3xl font-nsjp font-semibold text-white">
                Contact
              </h2>
            </button>
            <button id="blogscrollButton">
              <h2 className="text-3xl font-nsjp font-semibold text-white">
                Blog
              </h2>
            </button>
          </div>
        </header>
        {children}
        <footer className="text-center font-nsjp mb-8">
          ©2024 SoraBrog All rights reserved.
        </footer>
      </body>
    </html>
  );
}
